### ISSUE TITLE
Interpolation issues

### ISSUE THREAD

**Issue by vv-monsalve** [fridamedrano/Kalnia-Glaze#9]
The following reported for the latest colored font [KalniaColorVF.ttf](https://github.com/fridamedrano/Kalnia-Color/blob/main/paintcompiler-test/variable_ttf/KalniaColorVF.ttf) in the `paintcompiler-test` folder at commit `7f36f26`

<details><summary>⚠ <b>WARN:</b> Detect any interpolation issues in the font. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/interpolation_issues">com.google.fonts/check/interpolation_issues</a>)</summary><div>

>
>When creating a variable font, the designer must make sure that corresponding paths have the same start points across masters, as well as that corresponding component shapes are placed in the same order within a glyph across masters. If this is not done, the glyph will not interpolate correctly.
>
>Here we check for the presence of potential interpolation errors using the fontTools.varLib.interpolatable module.
>
* ⚠ **WARN** Interpolation issues were found in the font: 	- Contour 0 start point differs in glyph 'percent.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour order differs in glyph 'uni25CC': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370>, [15, 2, 4, 1, 6, 3, 8, 5, 10, 7, 12, 9, 14, 11, 0, 13] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>.

	- Contour 2 start point differs in glyph 'sterling.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'perthousand.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 6 start point differs in glyph 'perthousand.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 7 start point differs in glyph 'perthousand.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 1 start point differs in glyph 'percent' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 3 start point differs in glyph 'percent' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'percent' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 1 start point differs in glyph 'tilde' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 1 start point differs in glyph 'percent.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 3 start point differs in glyph 'percent.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 3 start point differs in glyph 'uni1E9E' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c280>

	- Contour 1 start point differs in glyph 'uni1E9E' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 3 start point differs in glyph 'uni1E9E' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 1 start point differs in glyph 'uni1E9E' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour 1 start point differs in glyph 'c.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'cent.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 2 start point differs in glyph 'section.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 3 start point differs in glyph 'section.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 2 start point differs in glyph 'section.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour 3 start point differs in glyph 'section.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour 0 start point differs in glyph 'tilde.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 2 start point differs in glyph 'uni1E9E.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c280>

	- Contour 0 start point differs in glyph 'uni1E9E.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 2 start point differs in glyph 'uni1E9E.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 0 start point differs in glyph 'uni1E9E.color1' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour order differs in glyph 'uni25CC.color0': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370>, [15, 2, 4, 1, 6, 3, 8, 5, 10, 7, 12, 9, 14, 11, 0, 13] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>.

	- Contour 4 start point differs in glyph 'perthousand.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 6 start point differs in glyph 'perthousand.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 7 start point differs in glyph 'perthousand.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'section' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 5 start point differs in glyph 'section' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'section' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour 5 start point differs in glyph 'section' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour order differs in glyph 'paragraph': [0, 1, 2, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370>, [0, 2, 1, 3] in <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>.

	- Contour 6 start point differs in glyph 'perthousand' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 8 start point differs in glyph 'perthousand' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 9 start point differs in glyph 'perthousand' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 0 start point differs in glyph 'breve.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 0 start point differs in glyph 'breve.color0' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5eaa0>

	- Contour 4 start point differs in glyph 'sterling' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 4 start point differs in glyph 'cent' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0>

	- Contour 2 start point differs in glyph 'c' between location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5f370> and location <fontTools.ttLib.ttGlyphSet._TTGlyphSetGlyf object at 0x108d5c4f0> [code: interpolation-issues]
</div></details>

**Comment by vv-monsalve** [comment]
Hi @fridamedrano, after pulling the latest source file at commit `b4893a0`, some interpolation issues were reported for the compiled font.

Please look over all the cases listed in the pdf report. The glyphs `Section`, `8` and `fk` ligature are showing some kinks and outlines issues.

[KalniaGlaze-2.pdf](https://github.com/user-attachments/files/15594372/KalniaGlaze-2.pdf)


### Section
<img width="2130" alt="Screen Shot 2024-06-05 at 12 02 43" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/f4f18e2d-e1c4-41fd-a35c-42ef1b6f5081">
<img width="2331" alt="Screen Shot 2024-06-05 at 12 03 17" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/56f8b76e-da96-4fb8-8230-9b3b1696a6db">
<img width="300" alt="Screen Shot 2024-06-05 at 12 11 34" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/3ee65811-4efa-4ff3-a6a1-0bb1174f0f2d">
<img width="300" alt="Screen Shot 2024-06-05 at 12 11 46" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/32761669-00df-4cff-8fdc-13b39d5c5e86">

### 8
<img width="2273" alt="Screen Shot 2024-06-05 at 12 04 21" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/ca9b9848-7340-4140-b827-6b6d42598a6c">
<img width="2086" alt="Screen Shot 2024-06-05 at 12 04 39" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/c504d17f-7f29-4bde-a911-1acfe74b1427">
<img width="400" alt="Screen Shot 2024-06-05 at 12 12 10" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/3821c852-86d0-4701-8ec8-565cdeb4b482">

### fk
<img width="1144" alt="Screen Shot 2024-06-05 at 12 07 38" src="https://github.com/fridamedrano/Kalnia-Glaze/assets/48698976/08d4a807-6abf-4f71-8852-240967b61647">

**Comment by fridamedrano** [comment]
fixes in the repository
